### ISSUE TITLE
Client crash using the Quantum Stabilizer

### ISSUE THREAD

**Issue by Giovanni-NL** [kyau/afterhours#4]
Had a client crash a minute or so after filling the Quantum Stabilizer with 16 of each Unstable Dark Matter, Gunpowder and Void Crystals.

`Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot set property PropertyBool{name=active, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockState{block=minecraft:air, properties=[]}
    at net.minecraft.block.state.BlockState$StateImplementation.func_177226_a(BlockState.java:156)
    at net.kyau.afterhours.blocks.QuantumStabilizer.setState(QuantumStabilizer.java:197)
    at net.kyau.afterhours.tileentity.TileEntityQuantumStabilizer.func_73660_a(TileEntityQuantumStabilizer.java:250)
    at net.minecraft.world.World.func_72939_s(World.java:1718)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2089)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

[AfterHours-stacktrace.txt](https://github.com/kyau/afterhours/files/170919/AfterHours-stacktrace.txt)

**Comment by Giovanni-NL** [comment]
I should add that this happened once.  The Quantum Stabilizer worked properly before and after the crash.

**Comment by Giovanni-NL** [comment]
And even more info:  The crash happened again.  Both times the crash occurred when I was flying across the map very fast (using the Gem armor from the [ProjectE](http://mods.curse.com/mc-mods/minecraft/226410-projecte) mod). So you may want to try that to reproduce this crash.

**Comment by kyau** [comment]
This should be fixed now I pushed some updates today the Stabilizer and Reciprocator should no longer crash the client when you exit render distance.

**Comment by Giovanni-NL** [comment]
Nice. If I could use emoticons here you'd get a thumbs up!  :)
